spring:
  datasource:
    url: jdbc:mysql://mysql.mysql:3306/app_prod
    username: app_prod
    password: ${DB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  h2:
    console:
      enabled: false

app:
  cors:
    allowed-origins: 
      - "https://claude-code-todoapp.yamac.net"

server:
  port: 8080