apiVersion: apps/v1
kind: Deployment
metadata:
  name: claude-code-todoapp-frontend
spec:
  selector:
    matchLabels:
      app: claude-code-todoapp-frontend
  template:
    metadata:
      labels:
        app: claude-code-todoapp-frontend
    spec:
      serviceAccountName: deployer
      containers:
        - name: claude-code-todoapp-frontend
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: claude-code-todoapp-frontend