apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: true
    pairs:
      app: claude-code-todoapp-frontend

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml