apiVersion: apps/v1
kind: Deployment
metadata:
  name: claude-code-todoapp-frontend
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: claude-code-todoapp-frontend
          image: cr.yamac.net/claude-code-todoapp/frontend:develop
          imagePullPolicy: Always
          resources:
            requests:
              memory: 50Mi
            limits:
              memory: 100Mi