apiVersion: apps/v1
kind: Deployment
metadata:
  name: claude-code-todoapp-backend
spec:
  selector:
    matchLabels:
      app: claude-code-todoapp-backend
  template:
    metadata:
      labels:
        app: claude-code-todoapp-backend
    spec:
      serviceAccountName: deployer
      containers:
        - name: claude-code-todoapp-backend
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: claude-code-todoapp-backend
            - secretRef:
                name: claude-code-todoapp-backend
