apiVersion: apps/v1
kind: Deployment
metadata:
  name: claude-code-todoapp-backend
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: claude-code-todoapp-backend
          image: cr.yamac.net/claude-code-todoapp/backend:develop
          imagePullPolicy: Always
          resources:
            requests:
              memory: 100Mi
            limits:
              memory: 200Mi
