apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: claude-code-todoapp-backend
spec:
  tls:
    - hosts:
        - "*.yamac-beta.net"
      secretName: yamac-beta-net-tls
  rules:
    - host: claude-code-todoapp-api.yamac-beta.net
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: claude-code-todoapp-backend
                port:
                  number: 8080
