apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app-beta

resources:
  - ./../../base
  - sealed-secret.yaml

patches:
  - path: configmap.yaml
  - path: deployment.yaml
  - path: ingress.yaml
